# Generated by Django 3.0.1 on 2019-12-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Produto')),
                ('tamanho', models.PositiveSmallIntegerField(choices=[(4, '4 GB'), (8, '8 GB'), (16, '16 GB'), (32, '32 GB'), (64, '64 GB')])),
            ],
            options={
                'verbose_name': 'Memória RAM',
                'verbose_name_plural': 'Memórias RAM',
            },
        ),
        migrations.CreateModel(
            name='PlacaDeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Produto')),
            ],
            options={
                'verbose_name': 'Placa de Vídeo',
                'verbose_name_plural': 'Placas de Vídeo',
            },
        ),
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Produto')),
                ('marca', models.CharField(choices=[('amd', 'AMD'), ('intel', 'Intel')], max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Processadores',
            },
        ),
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Produto')),
                ('slots_memoria', models.PositiveSmallIntegerField(verbose_name='Qtde. slots de memória RAM')),
                ('memoria_suportaca', models.PositiveSmallIntegerField(verbose_name='Total de memória RAM suportado')),
                ('video_integrado', models.BooleanField(verbose_name='Vídeo Integrado')),
                ('processadores_suportados', models.ManyToManyField(related_name='placas_com_suporte', to='computador.Processador')),
            ],
            options={
                'verbose_name': 'Placa Mãe',
                'verbose_name_plural': 'Placas Mãe',
            },
        ),
    ]
