# Generated by Django 3.0.1 on 2019-12-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='memoria',
        ),
        migrations.CreateModel(
            name='ComputadorMemoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoria', to='pedidos.Computador')),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computador', to='produtos.MemoriaRam', verbose_name='Memória RAM')),
            ],
        ),
    ]
