# Generated by Django 3.0.1 on 2019-12-22 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('memoria', models.ManyToManyField(to='produtos.MemoriaRam', verbose_name='Memória RAM')),
                ('placa_mae', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.PlacaMae', verbose_name='Placa Mãe')),
                ('placa_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.PlacaDeVideo', verbose_name='Placa de Vídeo')),
                ('processador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.Processador')),
            ],
            options={
                'verbose_name_plural': 'Computadores',
            },
        ),
    ]
